version: 2.1

workflows:
  version: 2.1
  build:
    jobs:
      - main-job

jobs:
  main-job:
    executor: main-exec
    steps:
      - checkout
      - configure-system
      - install-webauthn

executors:
  main-exec:
    # docker:
    #   - image: circleci/node:10
    #   - image: circleci/postgres:10
    machine:
      image: ubuntu-1604:202010-01
    environment:
      COOKIES: ~/cookies
      VERBOSE: brief
      HTTPD_ERROR_LOG: /var/log/apache2/error.log
      CHAISE_BASE_URL: http://localhost/chaise
      ERMREST_URL: http://localhost/ermrest
      SHARDING: "true"

commands:
  configure-system:
    steps:
      - run: lsb_release -a
      - run: export TZ=America/Los_Angeles
      - run: export PATH="$(systemd-path user-binaries):$PATH"
      - run: sudo su -c 'echo /usr/lib/python3.5/site-packages > /usr/local/lib/python3.5/dist-packages/sys-site-packages.pth'
      - run: sudo ln -s /etc/apache2/conf-enabled /etc/apache2/conf.d
      - run: sudo apt-get -y purge postgresql-9.1 postgresql-9.2 postgresql-9.3 postgresql-9.4 postgresql-9.5 postgresql-9.6 || true
      - run: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      - run: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main" > /etc/apt/sources.list.d/PostgreSQL.list'
      - run: sudo apt-get -y update
      - run: sudo apt-get install postgresql-10
      - run: sudo service postgresql start 10
      - run:
          name: Insatlling other stuff
          command: |
            sudo a2enmod ssl
            sudo a2ensite default-ssl
            sudo groupadd -o -g $(id -g www-data) apache
            sudo pip3 --version
            sudo su -c 'python3 -c "import site;print(site.PREFIXES);"'
            sudo su -c 'python3 -c "import site;print(site.getsitepackages())"'
            sudo pip3 install requests
            sudo pip3 install psycopg2-binary
            sudo pip3 install git+https://github.com/informatics-isi-edu/webpy.git
  install-webauthn:
    steps:
      - run:
          command: |
            sudo useradd -m -r webauthn
            sudo su -c '/usr/bin/python3 -c "import sys;import pprint;pprint.pprint(sys.path)"' - webauthn
            cd ..
            git clone https://github.com/informatics-isi-edu/webauthn.git
            cd webauthn
            sudo make testvars
            sudo make install
            sudo make deploy
            sudo bash ./test/ubuntu-travis-setup.sh
            sudo a2enmod webauthn
            sudo service apache2 restart

