version: 2.1

workflows:
  version: 2.1
  build:
    jobs:
      - main-job

jobs:
  main-job:
    executor: main-exec
    steps:
      - checkout
      - configure-system

executors:
  main-exec:
    machine:
      image: ubuntu-1604:202010-01
    environment:
      COOKIES: ~/cookies
      VERBOSE: brief
      HTTPD_ERROR_LOG: /var/log/apache2/error.log
      CHAISE_BASE_URL: http://localhost/chaise
      ERMREST_URL: http://localhost/ermrest
      SHARDING: "true"

commands:
  configure-system:
    steps:
        - run: 
            command: |
              export TZ=America/Los_Angeles
              export PATH="$(systemd-path user-binaries):$PATH"
              sudo su -c 'echo /usr/lib/python3.5/site-packages > /usr/local/lib/python3.5/dist-packages/sys-site-packages.pth'
              sudo ln -s /etc/apache2/conf-enabled /etc/apache2/conf.d
              sudo service postgresql stop || true
              sudo apt-get -y purge postgresql-9.1 postgresql-9.2 postgresql-9.3 postgresql-9.4 postgresql-9.5 postgresql-9.6 || true
              sudo service postgresql start 10
              sudo a2enmod ssl
              sudo a2ensite default-ssl
              sudo groupadd -o -g $(id -g www-data) apache
              sudo pip3 --version
              sudo su -c 'python3 -c "import site;print(site.PREFIXES);"'
              sudo su -c 'python3 -c "import site;print(site.getsitepackages())"'
              sudo pip3 install requests
              sudo pip3 install psycopg2-binary
              sudo pip3 install git+https://github.com/informatics-isi-edu/webpy.git
